name: CI Testing

on: [push]

jobs:
  install-and-test:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Confirm Node version
        run: node -v
      - name: Install deps and test
        run: |
          yarn
          yarn test
        env:
          CI: true
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
